baseURL: "https://gabnotes.org"
title: "Gab’s Notes"
paginate: 10
theme: "PaperMod"

languageCode: "en-us"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Gab’s Notes"
  description: "My take on tech-related subjects (but not only)."
  keywords: [blog, Gabriel, Augendre, tech, docker, golang, python, self-hosting]
#  author: "Gabriel Augendre"
  images: ["img/portrait.jpg"]
  DateFormat: "2006-01-02"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  ShowFullTextinRSS: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: true
  comments: true
  hidemeta: false
  hideSummary: false
  hideFooter: true
  showtoc: false
  tocopen: false

  schema:
    publisherType: 'Person'

  assets:
    disableHLJS: true
    theme_color: "#ffffff"
    msapplication_TileColor: "#226997"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: "Gab’s Notes"
    Content: |-
      My take on tech related subjects (but not only)

  socialIcons:
    - name: Email
      url: "mailto:ga-blog@augendre.info"
    - name: Mastodon
      url: "https://fosstodon.org/@Crocmagnon"
    - name: GitHub
      url: "https://github.com/Crocmagnon"
    - name: Gitea
      url: "https://git.augendre.info/gaugendre"
    - name: GitLab
      url: "https://gitlab.com/gaugendre"
    - name: CV
      url: "https://cv-gabriel.augendre.info"
    - name: StackOverflow
      url: "https://stackoverflow.com/users/2758732/gabriel"

  cover:
#    hidden: true # hide everywhere but not in structured data
#    hiddenInList: true # hide on list pages and home
#    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/Crocmagnon/hugo-blog/tree/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: about
      url: /about/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: search
      url: /search/
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
#pygmentsUseClasses: true
markup:
  highlight:
#    noClasses: true
    codeFences: true
    guessSyntax: true
#    lineNos: true
#    anchorLineNos: true
    style: catppuccin-macchiato

outputs:
  home:
    - HTML
    - RSS
    - JSON

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
